language: cpp
os:
- linux
- osx
- windows
dist: trusty
addons:
  apt:
    packages:
    - libudev-dev
env:
  global:
  - PREBUILD_TARGETS="14.0.0"
  - PREBUILD_ELECTRON_TARGETS="12.0.0 13.0.0"
  matrix:
  - ARCH="x64"
  - ARCH="ia32"
matrix:
  exclude:
  - os: linux
    env: ARCH="ia32"
  - os: osx
    env: ARCH="ia32"
before_install:
- |
  if [ $TRAVIS_OS_NAME == windows ]; then
    choco install nodejs-lts
    export PATH="/c/Program Files/nodejs:$PATH"
    export GYP_MSVS_VERSION=2015
  fi
- "$CXX --version"
- node --version
- npm --version
install:
- npm install
script:
- |
  for target in $PREBUILD_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH
  done

  for target in $PREBUILD_ELECTRON_TARGETS; do
    npm run prebuild -- -t $target --arch=$ARCH -r electron
  done
deploy:
  provider: releases
  api_key:
    secure: KeXWaJ+CrgieNrpnj45W03RFvs4Z4RwWa20Qi36gL8Bh3wE+VuTQ3gFZ+Qt1BFkdsFtS2fxMgXLn+5X6ZSHUS+mCoGbyYFpSe/nnH20MmbsZqtrEy8PTGC2TYyPcDfJYlGaW+rz9CJ88zINZrRDFbnDgzspBFst+534qWIMHmj+MoxQIxXkkHl5F7S1SxtEqv7KvNP+5zMnGmnlEeqkV8wMTrFd+tFn5tNiRzgmym2UMdzVcZSeMj2ma5A9uVhBhyLJQSQAiFJDm+aHKWqDjIoZ1lmOaYAqqoGoZ6Gh4vnX0mSpn2oFBj1UxnekKzBorCWcsojXMBtGZBu21kcvcmST6DxSvErOhlJigEMh2BlY8tlgSmpI47i3NiTHWD6YnKem7sI58wdIDYhIl4z2yQzFAAOKQH0gtmCEYbYXt/KXZcOQPVwtl/xX1MfWiLlue8RPmvjL+7Fv7Gy3jG5xCY80kqsCV/y3DxQ/BEvnGoG3ehGQQuLPGlRcbLBmVYSvzGbCEitrfSEhJjUH9wnGtMnjPcVAzzIDCRLbLgYQWpUnxFRocAOW+9DR/R8d+aE+07L0eNQJpOBElVDqxYF5HQpKPM4ny2/f7twZea3Nk2J+WvmugqtIjmSqIoJGtpG87PlUNHYSJevYBVUgFFwXraB00nMi+Bl7wsb5wA9/MgDY=
  file_glob: true
  file: prebuilds/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: lightspeedretail/node-usb
